parameters:

##### Defined Class


  austral.admin.path:                                       "austral-admin"
  austral.admin.project:
    name:                                                   "Austral"
    background:                                             "/bundles/australdesign/images/austral.jpg"
    forgot_enabled:                                         false
    copyright:                                              "Propulsed with ❤️ by <a href='https://austral.dev' target='_blank'>Austral</a>"
    deployment_api_key:                                     false

  austral.admin.download:
    creator:                                                "Austral"
    title_before:                                           "austral"
    trans_domain:                                           "austral"
    encode:                                                 "UTF-8"
    xlsTheme:
      enabled:                                              true
      header:
        color:                                              "#000000"
        background:                                         "#f0f0f0"
      content:
        color:                                              "#000000"
        background:                                         "#ffffff"

  austral.admin.modules.enabled.compression_gzip:           true

  austral.admin.language:
    user:                                                   ["en", "fr"]
    enabled_multi:                                          false
    list:                                                   []

  austral.admin.modules.data_reload_js:
    all:
      - "#header-master"
      - "#container-master"
    container:
      - "#header-master"
      - "#container-master"
    body:
      - "body"

  austral.admin.modules.actions.entities:
    list:
      default:        austral_admin_module_index
    edit:
      default:        austral_admin_module_form_edit
      language:       austral_admin_module_form_edit_language
    create:
      default:        austral_admin_module_form_create
      language:       austral_admin_module_form_create_language
    delete:
      default:        austral_admin_module_delete
      language:       austral_admin_module_delete_language
    truncate:
      default:        austral_admin_module_truncate
    duplicate:
      default:        austral_admin_module_duplicate
      language:       austral_admin_module_duplicate_language
    change:
      default:        austral_admin_module_change_value
      language:       austral_admin_module_change_value_language
    download:
      default:        austral_admin_module_download

  austral.admin.default.class:                              Austral\AdminBundle\Admin\DefaultAdmin
  austral.admin.data_hydrate.class:                         Austral\ListBundle\DataHydrate\DataHydrateORM