services:
  _defaults:
    autowire: true
    autoconfigure: true
    public:        true


##### Event Subscriber
  austral.admin.dashboard.event_subscriber:
    class:          Austral\AdminBundle\EventSubscriber\DashboardSubscriber
    arguments:      ["@request_stack"]
    tags:
      - { name: kernel.event_subscriber }

  austral.admin.configuration_checker.event_subscriber:
    class:          Austral\AdminBundle\EventSubscriber\ConfigurationCheckerSubscriber
    arguments:      ["@austral.tools.services.status-checker"]
    tags:
      - { name: kernel.event_subscriber }

  austral.admin.http.event_subscriber:
    class:          Austral\AdminBundle\EventSubscriber\HttpAdminEventSubscriber
    arguments:      [ "@service_container", "@austral.admin.config", "@austral.tools.debug" ]
    tags:
      - { name: kernel.event_subscriber }

  austral.admin.module.event_subscriber:
    class:          Austral\AdminBundle\EventSubscriber\ModuleEventSubscriber
    arguments:      [ "@translator", "@austral.http.domains.management", "@austral.entity_file.link.generator", "@austral.admin.config" ]
    tags:
      - { name: kernel.event_subscriber }

##### Configuration
  austral.admin.config:
    class:          Austral\AdminBundle\Configuration\AdminConfiguration
    arguments:      ["%austral_admin%"]

##### Modules
  austral.admin.modules:
    class:          Austral\AdminBundle\Module\Modules
    arguments:      [ "@service_container", "@event_dispatcher","@router", "@translator", "@austral.admin.config"]

##### Handler
  austral.admin.handler:
    class:          Austral\AdminBundle\Handler\AdminHandler
    arguments:      [ "@service_container", "@request_stack", "@event_dispatcher", "@austral.tools.debug"]

##### Downlaod
  austral.admin.download:
    class:          Austral\AdminBundle\Services\Download
    arguments:      [ "@austral.admin.config", "@translator" ]

##### Guideline
  austral.admin.guideline:
    class:          Austral\AdminBundle\Services\Guideline

##### Template
  austral.admin.template:
    class:          Austral\AdminBundle\Template\TemplateParameters
    arguments:      [ "@austral.admin.config" ]

##### Conflict Detect
  austral.admin.conflict_detect:
    class:          Austral\AdminBundle\Services\ConflictDetect
    arguments:      ["@austral.entity_manager.user", "@twig", "@austral.entity_file.link.generator", "@?austral.notify.mercure", "@?austral.notify.push"]